#filter
btn_filter ="xpath=//button[contains(@data-slot, 'popover-trigger') and contains(., 'Filter')]"
btn_hapus = "xpath=//button[@data-slot='popover-close' and .//span[text()='Hapus']]"
dropdown_status_aktif ="xpath=(//div[@role='dialog']//input)[1]"
dropdown_tipe ="xpath=(//div[@role='dialog']//input)[2]"
dropdown_status_seller ="xpath=(//div[@role='dialog']//input)[3]"
btn_tampilkan ="xpath=//button[@data-slot='popover-close' and .//span[text()='Tampilkan']]"
input_nama_customer ="xpath=//input[@placeholder='Ketik Nama Customer']"
dropdown_blacklist ="xpath=(//div[@role='dialog']//input)[8]"
input_no_customer = "xpath=//div[@role='dialog']//input[contains(@placeholder, 'Nomor Customer') or contains(@placeholder, 'No Customer')]"
input_email_customer = "xpath=//div[@role='dialog']//input[@placeholder='Ketik Email Customer']"
input_no_telp = "xpath=//div[@role='dialog']//input[@placeholder='Ketik No Telp']"
input_global_search = "xpath=//input[@placeholder='Search...']"
btn_konfirmasi_ubah = "xpath=//button[contains(., 'Ya, Konfirmasi')]"
btn_view_customer = "xpath=//button[@aria-label='view' or contains(., 'view')]"
switch_view_status = "xpath=//button[@role='switch']"
switch_inside_view_detail = "xpath=//div[not(ancestor::tr)]//button[@role='switch'] | //main//button[@role='switch']"
toast_status_updated = "xpath=//div[@data-title and text()='Update status customer sukses!']"

#input filter
input_customer_not_found = "ryan"
input_Nocustomer_notfound = "0821213"
input_customer="Budi"
input_partial="ard"
email_partial="yopmail"
no_partial="0806"
no_customer_value="00204036"
no_customer_input = "00204047"