#Search Tipe
input_search_tipe = "xpath=//input[@placeholder='Search...']"
keyword_search="110"
keyword_Invalid="UNKNOWN_TYPE"

#Filter Tipe
btn_filter_tipe = "xpath=//button[@data-slot='popover-trigger' and contains(., 'Filter')]"
Button_Status_Aktif= "xpath=(//div[@role='dialog'])[last()]//input[@placeholder='Cari..']"
opt_status="xpath=//button[.//span[text()='Aktif']]"
lelang_filter= "xpath=//input[@value='Pilih Objek Lelang']"
input_search_filter_lelang = "xpath=(//div[@role='dialog'])[last()]//input[@placeholder='Cari..']"
input_objek="Car"
opt_objek_lelang="xpath=(//div[@role='dialog'])[last()]//button[.//span[text()='Car']]"
merek_filter="xpath=//input[@value='Pilih Merek']"
input_search_merek="xpath=(//div[@role='dialog'])[last()]//input[@placeholder='Cari..']"
option_merek="xpath=(//div[@role='dialog'])[last()]//button[.//span[text()='MITSUBISHI']]"
input_merek="MITSUBISHI"
model_filter="xpath=//input[@value='Pilih Model']"
input_search_model="xpath=(//div[@role='dialog'])[last()]//input[@placeholder='Cari..']"
option_model="xpath=(//div[@role='dialog'])[last()]//button[.//span[text()='112']]"
input_model="112"
input_filter_ketik_tipe = "xpath=//input[@placeholder='Ketik Tipe']"
input_tipe="110"
btn_hapus_filter = "xpath=//button[@data-slot='popover-close' and .//span[text()='Hapus']]"
btn_tampilkan_filter = "xpath=//button[@data-slot='popover-close' and .//span[text()='Tampilkan']]"