#Search Edit Lokasi Unit
input_search_table = "xpath=//input[@placeholder='Search...']"
value_search_Nama="Pool Jakarta Central"

#Edit Lokasi Unit
btn_action_dropdown = "xpath=//button[@data-testid='dropdown-menu-trigger' or @aria-label='Tampilkan aksi lainnya']"
item_menu_edit = "xpath=//div[@role='menuitem' and contains(., 'edit')]"
input_lokasi_unit = "xpath=//input[@name='poolName']"
nama_lokasi_baru="Pool Jakarta Barat (Updated)"
input_nama_pic = "xpath=//input[@name='picName']"
nama_pic_baru="Ahmad Subagja"
input_nomor_pic = "xpath=//input[@name='picPhone']"
nomor_pic_baru="081298765432"
input_alamat_pool = "xpath=//input[@name='poolAddress']"
alamat_baru="Jl. Panjang No. 88"
input_latitude = "xpath=//input[@name='latitude']"
latitude_baru="-6.1901"
input_longitude = "xpath=//input[@name='longitude']"
longitude_baru="106.7621"
input_catatan = "xpath=//input[@name='notes']"
catatan_baru="Update lokasi cabang baru"
btn_simpan_modal = "xpath=//button[@data-slot='button' and contains(., 'Simpan')]"
btn_ya_konfirmasi = "xpath=//button[contains(., 'Ya, Konfirmasi')]"
toast_success_update_lokasi = "xpath=//li[@data-type='success']//div[contains(text(), 'Berhasil update data lokasi unit')]"