#Add Warna
btn_tambah_data = "xpath=//button[@data-slot='modal-trigger' and contains(., 'Tambah')]"
dropdown_objek_lelang = "xpath=//input[@value='Pilih Objek Lelang']"
input_search_objek_lelang = "xpath=//input[@placeholder='Cari..']"
option_objek_lelang_car = "xpath=//span[text()='Car']"
input_kode_warna = "xpath=//input[@name='colorCode']"
input_nama_warna = "xpath=//input[@name='colorName']"
input_hex_warna = "xpath=//input[@name='hex']"
btn_simpan = "xpath=//button[text()='Simpan']"
btn_ya_konfirmasi = "xpath=//button[contains(., 'Ya, Konfirmasi')]"
toast_success_create_warna = "xpath=//li[@data-type='success']//div[text()='Berhasil create data warna']"
err_wajib_diisi = "xpath=//p[contains(@class, 'text-danger') and text()='Wajib diisi']"
toast_error_hex_warna = "xpath=//li[@data-type='error']//div[contains(text(), 'Format hex warna salah')]"
toast_error_duplicate_code = "xpath=//li[@data-type='error']//div[contains(text(), 'Kode warna sudah digunakan')]"

#input warna
kode_warna="CLR-007"
objek_lelang="Car"
input_warna="Hijau"
hex_warna="#008000"
hex_warna_invalid="12345ZZ "