import os

#Search Seller
input_main_search = "xpath=//input[@placeholder='Cari']"
search_MOU="00000247"
btn_view_action = "xpath=//button[contains(@aria-label, 'View') or .//span[text()='visibility']]"
btn_tambah_sub_seller = "xpath=//button[span[text()='Tambah']] | //button[contains(., 'Tambah') and .//span[text()='add']]"
input_no_sub_seller = "xpath=//input[@name='addendumNumber' or @placeholder='Enter No Sub Seller']"
input_nama_sub_seller = "xpath=//input[@name='addendumName' or @placeholder='Enter Nama Sub Seller']"
input_cabang_jba      = "xpath=//input[@name='sellerBranch' or @placeholder='Enter Cabang JBA']"
btn_select_objek_lelang = "xpath=//div[span[contains(text(),'Choose Objek Lelang') or contains(text(),'Bike') or contains(text(),'Car') or contains(text(),'Electronic')]]"
btn_select_kategori="xpath=//div[span[contains(text(),'Choose Kategori Seller Javis') or contains(text(),'Gold Seller')]]"
izin_ubah_lot = "xpath=//div[p[text()='Izin Ubah Lot']]//div[label[text()='Ya']]/input"
btn_select_jenis_bidder = "xpath=//div[span[contains(text(),'Choose Jenis Bidder Lelang') or contains(text(),'Time Auction Normal') or contains(text(),'Regular')]]"
input_jam_lelang   = "xpath=//input[@name='auctionTimeDefault']"
input_durasi_lot   = "xpath=//input[@name='lotDurationDefault']"
input_waktu_tambahan = "xpath=//input[@name='additionalTimeDefault']"
input_kelipatan_bid  = "xpath=//input[@placeholder='Ketik Kelipatan Harga Bid']"
input_wanpres        = "xpath=//input[@name='wanpressDateDefault']"
input_jam_wanpres     = "xpath=//input[@name='wanpressTimeDefault']"
lelang_terbuka= "xpath=//div[p[text()='Lelang terbuka untuk customer Regular']]//div[label[text()='Ya']]/input"
input_harga_nipl     = "xpath=//input[@placeholder='Ketik Harga NIPL']"
btn_select_tipe_nipl = "xpath=//div[span[contains(text(),'Fix Price') or contains(text(),'Persentase') or contains(text(),'Choose')]]"
input_nominal_nipl   = "xpath=//input[@placeholder='Ketik Harga NIPL']/following::input[1]"
input_fee_lelang  = "xpath=//input[@name='auctionFee']"
input_ppn_rules   = "xpath=//input[@name='ppnRules']"
input_pph_rules   = "xpath=//input[@name='pphRules']"
input_ppn_buyers  = "xpath=//input[@name='pphBuyers']"
btn_select_include_ppn = "xpath=//div[span[contains(text(),'Pilih Include PPn')]]"
btn_select_include_pph = "xpath=//div[span[contains(text(),'Pilih Include PPh')]]"
btn_submit_tambah_sub_seller = "xpath=//button[normalize-space(text())='Tambah']"
btn_confirm_yes = "xpath=//button[normalize-space(text())='Yes']"
input_upload_file = "xpath=//input[@type='file']"
PATH_FOTO_1 = os.path.abspath(r"c:\Users\msi80\Downloads\sa1.jpeg")